apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordpress
  namespace: eks-project  # Explicitly specify the namespace
spec:
  replicas: 2
  selector:
    matchLabels:
      app: wordpress
  template:
    metadata:
      labels:
        app: wordpress
    spec:
      serviceAccountName: wordpress-sa  # Use the service account for Secrets Manager access
      containers:
        - name: wordpress
          image: 195275633219.dkr.ecr.us-east-1.amazonaws.com/eks-repo:wordpress-final
          # image: {{IMAGE}}  # Placeholder for ECR image, updated by CodePipeline
          ports:
            - containerPort: 80
          env:
            - name: WORDPRESS_DB_HOST
              valueFrom:
                secretKeyRef:
                  name: wordpress-db-credentials
                  key: WORDPRESS_DB_HOST
            - name: WORDPRESS_DB_USER
              valueFrom:
                secretKeyRef:
                  name: wordpress-db-credentials
                  key: WORDPRESS_DB_USER
            - name: WORDPRESS_DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: wordpress-db-credentials
                  key: WORDPRESS_DB_PASSWORD
            - name: WORDPRESS_DB_NAME
              valueFrom:
                secretKeyRef:
                  name: wordpress-db-credentials
                  key: WORDPRESS_DB_NAME
          resources:
            requests:
              memory: "256Mi"
              cpu: "200m"
            limits:
              memory: "512Mi"
              cpu: "500m"
