apiVersion: autoscaling/v2  # Use v2 for more flexibility
kind: HorizontalPodAutoscaler
metadata:
  name: wordpress-hpa
  namespace: eks-project
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: wordpress
  minReplicas: 2  # Minimum number of pods
  maxReplicas: 5 # Maximum number of pods
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 70  # Scale up if CPU usage exceeds 70% of requests